### ISSUE TITLE
работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [annazholnercik0391/Grid-template-project#1]
1)
невалидный стиль
![image](https://user-images.githubusercontent.com/8464662/111160867-31681400-85a3-11eb-986a-27751b40a768.png)

2)
цвет плейсхолдера не соовтетствует макету
![image](https://user-images.githubusercontent.com/8464662/111160664-fc5bc180-85a2-11eb-96a6-ea55aeeab48b.png)

3)
помоему сливается, не находите?
![image](https://user-images.githubusercontent.com/8464662/111160952-4775d480-85a3-11eb-9dd0-9c887efbfe9d.png)

**Comment by annazholnercik0391** [comment]
Исправила)
